/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112439-g44dc42e4ac-20231010"
#endif /* AVUTIL_FFVERSION_H */
