ID_DISCONNECTION_NOTIFICATION = 21
ID_NEW_INCOMING_CONNECTION  = 19
ID_INCOMPATIBLE_PROTOCOL_VERSION = 25
ID_CONNECTED_PING = 0
ID_UNCONNECTED_PING = 1
ID_CONNECTION_LOST = 22
ID_CONNECTION_REQUEST_ACCEPTED = 16
ID_CONNECTION_ATTEMPT_FAILED = 17

CommonPacketHandling = {}

InternalPacketHandling = {}

MainInfo = {
    guid = ""
}